{% set name = "evidently" %}
{% set version = "0.1.23.dev0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 836d3755ae60bdb918601e53757368537723e266ea23964208a0a4afcef5745e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - numpy
    - pandas
    - plotly
    - python >=3.6
    - pyyaml
    - requests
    - scikit-learn >=0.22.1
    - scipy
    - statsmodels

test:
  imports:
    - evidently
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
