{% set name = "evidently" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3bda2987d05e4de471fbfc6e11f45ca263fe0dfc47bf09078de423a55a9d72d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.6
    - numpy >=1.19.5
    - pandas >=1.1.5
    - plotly >=5.5.0
    - python >=3.6
    - pyyaml ~=5.1
    - requests >=2.19.0
    - scikit-learn >=0.24.0
    - scipy >=1.5.4
    - statsmodels >=0.12.2

test:
  imports:
    - evidently
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
