{% set name = "evidently" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 714ff4b7c3c6e7e1d76c15cd988b640eda31efc7cc967346117a4077e2fb7ca8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.6
    - nltk >=3.6.7
    - numpy >=1.19.5
    - pandas >=1.3.5
    - plotly >=5.5.0
    - pydantic <2
    - python >=3.6
    - pyyaml >=5.1
    - requests >=2.19.0
    - scikit-learn >=0.24.0
    - scipy >=1.5.4
    - statsmodels >=0.12.2
    - umap-learn >=0.5.3

test:
  imports:
    - evidently
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
