{% set name = "evidently" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49f3f5a724e65369f33243732dacd48aad68e3aa0bd66e3a8e7784ed5f675b5f

build:
  number: 0
  # umap-learn isn't available on s390x
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - nltk >=3.6.7
    - numpy >=1.19.5
    - pandas >=1.3.5
    - plotly >=5.5.0
    - pydantic >=1.9,<2
    - python
    - pyyaml >=5.1
    - requests >=2.19.0
    - scikit-learn >=0.24.0
    - scipy >=1.5.4
    - statsmodels >=0.12.2
    - umap-learn >=0.5.3

test:
  imports:
    - evidently
  source_files:
    - tests/*.py
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest tests -vv

about:
  home: https://github.com/evidentlyai/evidently
  dev_url: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  description: |
    Evidently is an open-source Python library for data scientists and ML engineers. 
    It helps evaluate, test, and monitor the performance of ML models from validation to production. 
    It works with tabular, text data and embeddings.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
