{% set name = "evidently" %}
{% set version = "0.4.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c07a65a5c07138708328dbdf1e2b369f725039f714efb393b5631db7b57fa393
  patches:
    - 0001-patch-test-to-exclude-experimental-features.patch

build:
  number: 0
  # umap-learn isn't available on s390x
  skip: True  # [py<37 or s390x]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    # removing experimental features that are dependent on missing chromadb
    - rm -rf $SP_DIR/evidently/experimental

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - plotly >=5.10.0
    - statsmodels >=0.12.2
    - scikit-learn >=1.0.1
    - pandas >=1.3.5
    - numpy >=1.22.0,<2.1
    - nltk >=3.6.7
    - scipy >=1.10.0
    - requests >=2.32.0
    - PyYAML >=5.4
    - pydantic >=1.10.13
    - litestar >=2.8.3
    - typing_inspect >=0.9.0
    - uvicorn >=0.22.0
    - watchdog >=3.0.0
    - typer >=0.3
    - rich >=13
    - iterative-telemetry >=0.0.5
    - dynaconf >=3.2.4
    - certifi >=2024.7.4
    - urllib3 >=1.26.19
    - fsspec >=2024.6.1
    - ujson >=5.4.0
    - deprecation >=2.1.0
    - uuid6 >=2024.7.10
    - cryptography >=43.0.1
  # from https://github.com/evidentlyai/evidently/blob/cd6cbfba3f0c0ebdb7494e53941d954272f451fa/requirements.min.txt#L30
  run_constrained:
    - openai >=1.16.2
    - evaluate >=0.4.1
    - transformers >=4.39.3
    - sentence-transformers >=2.7.0
    - chromadb >=0.4.0

# we don't include setup.py in the package
{% set tests_to_ignore = "--ignore=tests/test_setup.py" %}
# missing pyspark
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/spark/metrics/test_data_drift.py" %}
# missing chromadb
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/test_pydantic_aliases.py" %}
# this test tests the import of every single python file inside the package
# seems pretty unnecessary, it also breaks because of RecursionError: maximum recursion depth exceeded
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/test_pydantic_compat.py" %}

test:
  imports:
    - evidently
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - ipython
    - pytorch
    - pillow>=10.3.0
    - setuptools <=65.5.1 # [py<312]
    - setuptools ==68.2.2 # [py>=312]
    # To fix `from numba.np.ufunc import _internal SystemError: initialization of _internal failed without raising an exception`
    - numba >=0.57.0
  commands:
    # skipping pip check since it detects uuid6 0.0.0.dev0 when uuid6==2024.7.10 is used
    #- pip check
    - pytest {{ tests_to_ignore }} tests -vv

about:
  home: https://github.com/evidentlyai/evidently
  dev_url: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  description: |
    Evidently is an open-source Python library for data scientists and ML engineers. 
    It helps evaluate, test, and monitor the performance of ML models from validation to production. 
    It works with tabular, text data and embeddings.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
