{% set name = "evidently" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b23797f1cfea6c49971d4416f8569833b1683b83505b064c87d0d034570d156c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - numpy
    - pandas
    - plotly
    - python >=3.6
    - pyyaml
    - requests
    - scikit-learn >=0.22.1
    - scipy <=1.6.3
    - statsmodels

test:
  imports:
    - evidently
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
