{% set name = "evidently" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 743f31fe218f0b6a0c35aabe8f417f720c0fb9a9343f194f4e184b600e50628a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses >=0.6
    - nltk >=3.6.7
    - numpy >=1.19.5
    - pandas >=1.3.5
    - plotly >=5.5.0
    - python >=3.6
    - pyyaml ~=5.1
    - requests >=2.19.0
    - scikit-learn >=0.24.0
    - scipy >=1.5.4
    - statsmodels >=0.12.2

test:
  imports:
    - evidently
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
